### ISSUE TITLE
New Zealand Holidays

### ISSUE THREAD

**Issue by mrfrase3** [commenthol/date-holidays#288]
I've just had a bug ticket come across from New Zealand, where they have 16 regions and one island with "regional powers", but only 12 (including the island) have regional holidays and there are only 12 regions in the data for NZ.

The missing regions with no regional holidays are:
  - WKO - Waikato,
  - BOP - Bay of Plenty
  - GIS - Gisborne
  - MWT - Manawatu-Wanganui
  - TAS - Tasman

Is this correct? Are regions without holidays left out intentionally, or should I make a PR to add the missing regions with no dates listed?

https://www.govt.nz/browse/work/public-holidays-and-work/public-holidays-and-anniversary-dates/
https://en.wikipedia.org/wiki/Regions_of_New_Zealand#List_of_regions

**Comment by commenthol** [comment]
Hi @mrfrase3, 
Feel free to complete the missing regions.
Your PR is very welcome.

**Comment by mrfrase3** [comment]
There is also the new national holiday, Matariki, that should start next year given that the legislation passes, which it most likely will given the labour party's overwhelming majority.

It is based on a lunar calendar, which a committee has used to recommend dates for the next 30 years:
https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf

**Comment by commenthol** [comment]
The Maori lunar calendar looks very interesting. But implementing a calendar for one holiday (which also requires human interaction) is maybe not the way to go. Therefore I'd propose to add this Holiday as a series:
```yaml
'2022-06-24':
  name:
    en: Matariki
'2023-07-14':
  name:
    en: Matariki
'2024-06-28':
  name:
    en: Matariki
'2025-06-20':
  name:
    en: Matariki
'2026-07-10':
  name:
    en: Matariki
'2027-06-25':
  name:
    en: Matariki
'2028-07-14':
  name:
    en: Matariki
'2029-07-06':
  name:
    en: Matariki
'2030-06-21':
  name:
    en: Matariki
'2031-07-11':
  name:
    en: Matariki
'2032-07-02':
  name:
    en: Matariki
'2033-06-24':
  name:
    en: Matariki
'2034-07-07':
  name:
    en: Matariki
'2035-06-29':
  name:
    en: Matariki
'2036-07-21':
  name:
    en: Matariki
'2037-07-10':
  name:
    en: Matariki
'2038-06-25':
  name:
    en: Matariki
'2039-07-15':
  name:
    en: Matariki
'2040-07-06':
  name:
    en: Matariki
'2041-07-19':
  name:
    en: Matariki
'2042-07-11':
  name:
    en: Matariki
'2043-07-03':
  name:
    en: Matariki
'2044-06-24':
  name:
    en: Matariki
'2045-07-07':
  name:
    en: Matariki
'2046-06-29':
  name:
    en: Matariki
'2047-07-19':
  name:
    en: Matariki
'2048-07-03':
  name:
    en: Matariki
'2049-06-25':
  name:
    en: Matariki
'2050-07-15':
  name:
    en: Matariki
'2051-06-30':
  name:
    en: Matariki
'2052-06-21':
  name:
    en: Matariki
```
In case that there are overlapping regions for one or the other holiday you may want to add that as a note. See https://github.com/commenthol/date-holidays/blob/01d95c6a508b499f7ecea4d229bfd3b406dda912/data/countries/CH.yaml#L320-L321
