### ISSUE TITLE
Regarding the change of Korean holiday substitution law since 2014

### ISSUE THREAD

**Issue by prodzpod** [commenthol/date-holidays#300]
[Here's what I'm trying to do.](https://gist.github.com/prodzpod/f373fcf6ce30941be66c98425790e4b6) As you can see, there are two problems with this set right now.

- Firstly, 'P3D' does not 'center' the holiday, despite the actual definition of the holiday being 'take a day off 1 day before and after', this is minor as it can be manually adjusted post-calling, but it does mean the data is not entirely accurate as it's now pointing at the day before the actual holiday. (Note that 01-01 P3D does not have the comment, as the holiday is at 01-01 and up to 2 days after it were off, unlike the other 3-day-long holidays.)
- More importantly, Due to [Regulations on public holidays in public offices](https://www.law.go.kr/%EB%B2%95%EB%A0%B9/%EA%B4%80%EA%B3%B5%EC%84%9C%EC%9D%98%20%EA%B3%B5%ED%9C%B4%EC%9D%BC%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B7%9C%EC%A0%95), Korean holidays have adopted a substitution system. there are two types of systems:
  - (for 3-day-long holidays) If any day of the 3-day span overlaps with Sunday or other public holidays, make the next non-(sunday or public holiday) into substitution holiday.
  - (for others) If it overlaps with Saturday, Sunday or other public holidays, make the next non-(sunday or public holiday) into substitution holiday.

The [specification](https://github.com/commenthol/date-holidays/blob/master/docs/specification.md) does not seem to have an 'overlap-detection' and 'next working day' syntax, and the current change requires it.

**Comment by commenthol** [comment]
Hi @prodzpod, Maybe it is best to split up the 3day holiday period into 3 single days with their own rule.

**Comment by prodzpod** [comment]
This does fix the 'center' problem. However, the [substitution problem persists.](https://github.com/prodzpod/date-holidays/blob/kr-substitution/data/countries/KR.yaml#L58)

AFAIK, there is no way to detect if a holiday will end up on another holiday ('MM-DD', 'MM-DE if MM-DD is public holiday' detect itself and freaks out), and there is no way to place a holiday on next workday since the date. they are labeled "holiday" and "workday" in where <weekday> would go in the link.

**Comment by commenthol** [comment]
Maybe this rule does fit the needs?
```yaml
      korean 01-0-00:
        name:
          en: Korean New Year
          ko: 설날
      substitutes korean 01-0-00 and if Saturday,Sunday then next Tuesday:
        substitute: true
        name:
          en: Korean New Year
          ko: 설날
      korean 01-0-01:
        name:
          en: Korean New Year
          ko: 설날
      substitutes korean 01-0-01 and if Saturday then next Monday if Sunday then next Wednesday:
        substitute: true
        name:
          en: Korean New Year
          ko: 설날
      korean 01-0-02:
        name:
          en: Korean New Year
          ko: 설날
      substitutes korean 01-0-02 and if Saturday then next Monday if Sunday then next Tuesday:
        substitute: true
        name:
          en: Korean New Year
          ko: 설날
```
